### ISSUE TITLE
2023年底前更新的软件打包上传。

### ISSUE THREAD

**Issue by pchuan98** [Simscop/PublicArchive#1]
将年初这一版本的转盘软件打包并且添加对应的Release 信息。

**Comment by pchuan98** [comment]
@Augenstern01 你需要给我具体的release链接

**Comment by Augenstern01** [comment]
@pchuan98 https://github.com/Simscop/spindisk_andor/releases/tag/v1.1.0.1 这是release发布链接
安装包已上传至nas 团队文件-02产品研发\02 产品研发\SCOP002转盘共聚焦显微镜\软件安装包

**Comment by pchuan98** [comment]
![image](https://github.com/Simscop/PublicArchive/assets/32349458/a188baa6-878a-475a-b8e7-1c28ef58188a)

@Augenstern01 请提交更加详细的内容

**Comment by Augenstern01** [comment]
@pchuan98 https://github.com/Simscop/spindisk_andor/releases/tag/v1.1.0.1


![Image](https://github.com/Simscop/PublicArchive/assets/99737735/3b8c0bb9-1108-4878-b453-d495f954411a)

已更新的发布版本

**Comment by pchuan98** [comment]
验收通过。@Augenstern01
